// ==============================================================================
// Sovereign Glyph Engine - Static Catalog Dataset
// Comprehensive Unicode Emoji Registry with Synonyms, Tags, & Emoticons
// ==============================================================================

use super::{Category, EmojiEntry};

pub static CATALOG: &[EmojiEntry] = &[
    // -------------------------------------------------------------------------
    // Smileys & Emotion
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "😀",
        name: "grinning face",
        shortcode: "grinning",
        category: Category::Smileys,
        tags: &["happy", "smile", "joy", "grin"],
        emoticons: &[":D", ":-D"],
    },
    EmojiEntry {
        glyph: "😃",
        name: "grinning face with big eyes",
        shortcode: "smiley",
        category: Category::Smileys,
        tags: &["happy", "joy", "cheerful", "smile"],
        emoticons: &["=)"],
    },
    EmojiEntry {
        glyph: "😄",
        name: "grinning face with smiling eyes",
        shortcode: "smile",
        category: Category::Smileys,
        tags: &["happy", "joy", "laugh", "glad"],
        emoticons: &[":)", ":-)"],
    },
    EmojiEntry {
        glyph: "😁",
        name: "beaming face with smiling eyes",
        shortcode: "grin",
        category: Category::Smileys,
        tags: &["teeth", "smile", "proud", "beaming"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😆",
        name: "grinning squinting face",
        shortcode: "laughing",
        category: Category::Smileys,
        tags: &["xd", "haha", "giggle", "glad"],
        emoticons: &["xD", "XD"],
    },
    EmojiEntry {
        glyph: "😅",
        name: "grinning face with sweat",
        shortcode: "sweat_smile",
        category: Category::Smileys,
        tags: &["phew", "relief", "nervous", "close call"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤣",
        name: "rolling on the floor laughing",
        shortcode: "rofl",
        category: Category::Smileys,
        tags: &["lol", "hilarious", "crying", "floor"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😂",
        name: "face with tears of joy",
        shortcode: "joy",
        category: Category::Smileys,
        tags: &["tears", "lmao", "lol", "crying", "haha"],
        emoticons: &[":')"],
    },
    EmojiEntry {
        glyph: "🙂",
        name: "slightly smiling face",
        shortcode: "slightly_smiling",
        category: Category::Smileys,
        tags: &["polite", "fine", "calm", "modest"],
        emoticons: &[":)"],
    },
    EmojiEntry {
        glyph: "🙃",
        name: "upside-down face",
        shortcode: "upside_down",
        category: Category::Smileys,
        tags: &["silly", "sarcasm", "irony", "goofy"],
        emoticons: &["(:", "(-:"],
    },
    EmojiEntry {
        glyph: "😉",
        name: "winking face",
        shortcode: "wink",
        category: Category::Smileys,
        tags: &["flirt", "hint", "joke", "secret"],
        emoticons: &[";)", ";-)"],
    },
    EmojiEntry {
        glyph: "😊",
        name: "smiling face with smiling eyes",
        shortcode: "blush",
        category: Category::Smileys,
        tags: &["sweet", "content", "warm", "shy"],
        emoticons: &["^_^"],
    },
    EmojiEntry {
        glyph: "😇",
        name: "smiling face with halo",
        shortcode: "innocent",
        category: Category::Smileys,
        tags: &["angel", "saint", "pure", "holy"],
        emoticons: &["O:)", "O:-)"],
    },
    EmojiEntry {
        glyph: "🥰",
        name: "smiling face with hearts",
        shortcode: "smiling_face_with_3_hearts",
        category: Category::Smileys,
        tags: &["love", "adore", "crush", "in love"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😍",
        name: "smiling face with heart-eyes",
        shortcode: "heart_eyes",
        category: Category::Smileys,
        tags: &["love", "infatuation", "gorgeous", "adore"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤩",
        name: "star-struck",
        shortcode: "star_struck",
        category: Category::Smileys,
        tags: &["stars", "amazed", "wow", "fascinated", "fan"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😘",
        name: "face blowing a kiss",
        shortcode: "kissing_heart",
        category: Category::Smileys,
        tags: &["kiss", "love", "affection", "mwah"],
        emoticons: &[":*", ":-*"],
    },
    EmojiEntry {
        glyph: "😋",
        name: "face savoring food",
        shortcode: "yum",
        category: Category::Smileys,
        tags: &["delicious", "tasty", "nom", "lick"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😛",
        name: "face with tongue",
        shortcode: "stuck_out_tongue",
        category: Category::Smileys,
        tags: &["playful", "silly", "tease"],
        emoticons: &[":p", ":P", ":-p", ":-P"],
    },
    EmojiEntry {
        glyph: "😜",
        name: "winking face with tongue",
        shortcode: "stuck_out_tongue_winking_eye",
        category: Category::Smileys,
        tags: &["crazy", "wack", "joke", "prank"],
        emoticons: &[";p", ";P", ";-p", ";-P"],
    },
    EmojiEntry {
        glyph: "🤪",
        name: "zany face",
        shortcode: "zany",
        category: Category::Smileys,
        tags: &["wild", "goofy", "nuts", "party"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤑",
        name: "money-mouth face",
        shortcode: "money_mouth",
        category: Category::Smileys,
        tags: &["rich", "dollar", "wealth", "cash", "paid"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤗",
        name: "smiling face with open hands",
        shortcode: "hugs",
        category: Category::Smileys,
        tags: &["hug", "welcome", "open", "embrace"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤫",
        name: "shushing face",
        shortcode: "shush",
        category: Category::Smileys,
        tags: &["quiet", "secret", "silence", "hush"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤔",
        name: "thinking face",
        shortcode: "thinking",
        category: Category::Smileys,
        tags: &["hmm", "consider", "wonder", "ponder", "curious"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🫡",
        name: "saluting face",
        shortcode: "salute",
        category: Category::Smileys,
        tags: &["respect", "yes sir", "honor", "roger", "duty"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤐",
        name: "zipper-mouth face",
        shortcode: "zipper_mouth",
        category: Category::Smileys,
        tags: &["sealed", "silent", "secret", "confidential"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤨",
        name: "face with raised eyebrow",
        shortcode: "raised_eyebrow",
        category: Category::Smileys,
        tags: &["skeptical", "suspicious", "doubt", "really"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😐",
        name: "neutral face",
        shortcode: "neutral_face",
        category: Category::Smileys,
        tags: &["meh", "blank", "poker face", "deadpan"],
        emoticons: &[":|", ":-|"],
    },
    EmojiEntry {
        glyph: "😑",
        name: "expressionless face",
        shortcode: "expressionless",
        category: Category::Smileys,
        tags: &["unimpressed", "bored", "flat"],
        emoticons: &["-_-", "-__-", "-_"],
    },
    EmojiEntry {
        glyph: "😶",
        name: "face without mouth",
        shortcode: "no_mouth",
        category: Category::Smileys,
        tags: &["speechless", "mute", "quiet"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😏",
        name: "smirking face",
        shortcode: "smirk",
        category: Category::Smileys,
        tags: &["smug", "sly", "flirt", "knowing"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😒",
        name: "unamused face",
        shortcode: "unamused",
        category: Category::Smileys,
        tags: &["displeased", "annoyed", "grumpy"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🙄",
        name: "face with rolling eyes",
        shortcode: "roll_eyes",
        category: Category::Smileys,
        tags: &["eyeroll", "whatever", "frustration", "sarcastic"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😬",
        name: "grimacing face",
        shortcode: "grimacing",
        category: Category::Smileys,
        tags: &["awkward", "oops", "nervous", "yikes"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤥",
        name: "lying face",
        shortcode: "liar",
        category: Category::Smileys,
        tags: &["pinocchio", "false", "fake", "cap"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😌",
        name: "relieved face",
        shortcode: "relieved",
        category: Category::Smileys,
        tags: &["peaceful", "calm", "zen", "content"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😔",
        name: "pensive face",
        shortcode: "pensive",
        category: Category::Smileys,
        tags: &["sad", "regret", "depressed", "sorry"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😪",
        name: "sleepy face",
        shortcode: "sleepy",
        category: Category::Smileys,
        tags: &["tired", "exhausted", "snooze"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😴",
        name: "sleeping face",
        shortcode: "sleeping",
        category: Category::Smileys,
        tags: &["zzz", "asleep", "rest", "bed", "night"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😷",
        name: "face with medical mask",
        shortcode: "mask",
        category: Category::Smileys,
        tags: &["sick", "doctor", "health", "virus"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤒",
        name: "face with thermometer",
        shortcode: "thermometer_face",
        category: Category::Smileys,
        tags: &["fever", "ill", "sick"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤕",
        name: "face with head-bandage",
        shortcode: "head_bandage",
        category: Category::Smileys,
        tags: &["hurt", "injured", "accident"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤢",
        name: "nauseated face",
        shortcode: "nauseated",
        category: Category::Smileys,
        tags: &["disgust", "gross", "barf", "sick"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤮",
        name: "face vomiting",
        shortcode: "vomiting",
        category: Category::Smileys,
        tags: &["puke", "throw up", "gross"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥵",
        name: "hot face",
        shortcode: "hot_face",
        category: Category::Smileys,
        tags: &["sweat", "heat", "summer", "overheated"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥶",
        name: "cold face",
        shortcode: "cold_face",
        category: Category::Smileys,
        tags: &["freezing", "ice", "winter", "chilly"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥴",
        name: "woozy face",
        shortcode: "woozy",
        category: Category::Smileys,
        tags: &["dizzy", "tipsy", "drunk", "dazed"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😵",
        name: "knocked-out face",
        shortcode: "dizzy_face",
        category: Category::Smileys,
        tags: &["faint", "passed out", "stunned"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤯",
        name: "exploding head",
        shortcode: "exploding_head",
        category: Category::Smileys,
        tags: &["mindblown", "shock", "unbelievable", "boom"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤠",
        name: "cowboy hat face",
        shortcode: "cowboy",
        category: Category::Smileys,
        tags: &["western", "howdy", "sheriff"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥳",
        name: "partying face",
        shortcode: "partying",
        category: Category::Smileys,
        tags: &["celebration", "birthday", "cheers", "horns"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😎",
        name: "smiling face with sunglasses",
        shortcode: "sunglasses",
        category: Category::Smileys,
        tags: &["cool", "boss", "swag", "smooth"],
        emoticons: &["8)", "8-)", "B)", "B-)"],
    },
    EmojiEntry {
        glyph: "🤓",
        name: "nerd face",
        shortcode: "nerd",
        category: Category::Smileys,
        tags: &["geek", "glasses", "smart", "code", "coder"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🧐",
        name: "face with monocle",
        shortcode: "monocle",
        category: Category::Smileys,
        tags: &["classy", "examine", "scrutinize", "curious"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😕",
        name: "confused face",
        shortcode: "confused",
        category: Category::Smileys,
        tags: &["puzzled", "uncertain", "huh"],
        emoticons: &[":\\", ":-\\", ":/"],
    },
    EmojiEntry {
        glyph: "😟",
        name: "worried face",
        shortcode: "worried",
        category: Category::Smileys,
        tags: &["nervous", "anxious", "concern"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🙁",
        name: "slightly frowning face",
        shortcode: "frown",
        category: Category::Smileys,
        tags: &["sad", "disappointed", "bummed"],
        emoticons: &[":(", ":-("],
    },
    EmojiEntry {
        glyph: "😮",
        name: "face with open mouth",
        shortcode: "open_mouth",
        category: Category::Smileys,
        tags: &["surprise", "gasp", "whoa"],
        emoticons: &[":o", ":-o", ":O", ":-O"],
    },
    EmojiEntry {
        glyph: "😲",
        name: "astonished face",
        shortcode: "astonished",
        category: Category::Smileys,
        tags: &["shocked", "amazed", "speechless"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😳",
        name: "flushed face",
        shortcode: "flushed",
        category: Category::Smileys,
        tags: &["embarrassed", "blushing", "caught"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥺",
        name: "pleading face",
        shortcode: "pleading",
        category: Category::Smileys,
        tags: &["beg", "puppy eyes", "please", "cute"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥹",
        name: "face holding back tears",
        shortcode: "holding_back_tears",
        category: Category::Smileys,
        tags: &["touched", "grateful", "emotional", "pride"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😨",
        name: "fearful face",
        shortcode: "fearful",
        category: Category::Smileys,
        tags: &["scared", "spooked", "nervous"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😰",
        name: "anxious face with sweat",
        shortcode: "cold_sweat",
        category: Category::Smileys,
        tags: &["stressed", "panic", "sweat"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😥",
        name: "sad but relieved face",
        shortcode: "disappointed_relieved",
        category: Category::Smileys,
        tags: &["close", "sigh", "relief"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😢",
        name: "crying face",
        shortcode: "cry",
        category: Category::Smileys,
        tags: &["tear", "sad", "unhappy", "depressed"],
        emoticons: &[":'("],
    },
    EmojiEntry {
        glyph: "😭",
        name: "loudly crying face",
        shortcode: "sob",
        category: Category::Smileys,
        tags: &["bawling", "heartbroken", "screaming"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😱",
        name: "face screaming in fear",
        shortcode: "scream",
        category: Category::Smileys,
        tags: &["horror", "munch", "yikes", "terrified"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😖",
        name: "confounded face",
        shortcode: "confounded",
        category: Category::Smileys,
        tags: &["quiver", "frustrated", "suffering"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😣",
        name: "persevering face",
        shortcode: "persevere",
        category: Category::Smileys,
        tags: &["endure", "struggle", "holding on"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😞",
        name: "disappointed face",
        shortcode: "disappointed",
        category: Category::Smileys,
        tags: &["down", "regret", "sad", "defeat"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😓",
        name: "downcast face with sweat",
        shortcode: "sweat",
        category: Category::Smileys,
        tags: &["hard work", "exhausted", "tired"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😩",
        name: "weary face",
        shortcode: "weary",
        category: Category::Smileys,
        tags: &["drained", "can't even", "fed up"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😫",
        name: "tired face",
        shortcode: "tired_face",
        category: Category::Smileys,
        tags: &["exhaustion", "done", "sleep needed"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥱",
        name: "yawning face",
        shortcode: "yawn",
        category: Category::Smileys,
        tags: &["sleepy", "boring", "bedtime"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😤",
        name: "face with steam from nose",
        shortcode: "triumph",
        category: Category::Smileys,
        tags: &["determined", "proud", "fuming", "huff"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😡",
        name: "enraged face",
        shortcode: "rage",
        category: Category::Smileys,
        tags: &["angry", "mad", "pissed", "furious"],
        emoticons: &[">:(", ">:-("],
    },
    EmojiEntry {
        glyph: "😠",
        name: "angry face",
        shortcode: "angry",
        category: Category::Smileys,
        tags: &["mad", "annoyed", "irritated"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤬",
        name: "face with symbols on mouth",
        shortcode: "cursing",
        category: Category::Smileys,
        tags: &["profanity", "swear", "furious", "censored"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "😈",
        name: "smiling face with horns",
        shortcode: "smiling_imp",
        category: Category::Smileys,
        tags: &["devil", "evil", "mischief", "naughty"],
        emoticons: &["3:)", "3:-)"],
    },
    EmojiEntry {
        glyph: "👿",
        name: "angry face with horns",
        shortcode: "imp",
        category: Category::Smileys,
        tags: &["demon", "furious devil", "wrath"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💀",
        name: "skull",
        shortcode: "skull",
        category: Category::Smileys,
        tags: &["dead", "dying", "skeleton", "danger", "rip"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "☠️",
        name: "skull and crossbones",
        shortcode: "skull_and_crossbones",
        category: Category::Smileys,
        tags: &["poison", "pirate", "lethal", "toxic"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💩",
        name: "pile of poo",
        shortcode: "poop",
        category: Category::Smileys,
        tags: &["crap", "turd", "shit", "funny"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤡",
        name: "clown face",
        shortcode: "clown",
        category: Category::Smileys,
        tags: &["fool", "circus", "silly", "joke"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👻",
        name: "ghost",
        shortcode: "ghost",
        category: Category::Smileys,
        tags: &["spooky", "boo", "halloween", "spirit"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👽",
        name: "alien",
        shortcode: "alien",
        category: Category::Smileys,
        tags: &["extraterrestrial", "ufo", "space", "martian"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤖",
        name: "robot",
        shortcode: "robot",
        category: Category::Smileys,
        tags: &["bot", "ai", "machine", "android", "droid"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Gestures & Hands
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "👋",
        name: "waving hand",
        shortcode: "wave",
        category: Category::Gestures,
        tags: &["hello", "hi", "bye", "goodbye", "farewell"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤚",
        name: "raised back of hand",
        shortcode: "raised_back_of_hand",
        category: Category::Gestures,
        tags: &["stop", "halt", "high five"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "✋",
        name: "raised hand",
        shortcode: "hand",
        category: Category::Gestures,
        tags: &["stop", "pause", "wait", "high five"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🖖",
        name: "vulcan salute",
        shortcode: "vulcan",
        category: Category::Gestures,
        tags: &["spock", "star trek", "live long and prosper"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👌",
        name: "ok hand",
        shortcode: "ok_hand",
        category: Category::Gestures,
        tags: &["perfect", "fine", "approved", "zero"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤌",
        name: "pinched fingers",
        shortcode: "pinched_fingers",
        category: Category::Gestures,
        tags: &["italian", "chef kiss", "what do you want"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "✌️",
        name: "victory hand",
        shortcode: "peace",
        category: Category::Gestures,
        tags: &["victory", "peace sign", "two", "deuces"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤞",
        name: "crossed fingers",
        shortcode: "fingers_crossed",
        category: Category::Gestures,
        tags: &["luck", "hopeful", "wish"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤟",
        name: "love-you gesture",
        shortcode: "love_you_gesture",
        category: Category::Gestures,
        tags: &["ily", "asl", "affection"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤘",
        name: "sign of the horns",
        shortcode: "rock",
        category: Category::Gestures,
        tags: &["metal", "rock on", "horns", "concert"],
        emoticons: &["\\m/"],
    },
    EmojiEntry {
        glyph: "🤙",
        name: "call me hand",
        shortcode: "call_me",
        category: Category::Gestures,
        tags: &["shaka", "hang loose", "phone"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👈",
        name: "backhand index pointing left",
        shortcode: "point_left",
        category: Category::Gestures,
        tags: &["left", "direction"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👉",
        name: "backhand index pointing right",
        shortcode: "point_right",
        category: Category::Gestures,
        tags: &["right", "direction", "check this"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👆",
        name: "backhand index pointing up",
        shortcode: "point_up_2",
        category: Category::Gestures,
        tags: &["up", "above", "this"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🖕",
        name: "middle finger",
        shortcode: "middle_finger",
        category: Category::Gestures,
        tags: &["fu", "flip off", "rude"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👇",
        name: "backhand index pointing down",
        shortcode: "point_down",
        category: Category::Gestures,
        tags: &["down", "below", "read below"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "☝️",
        name: "index pointing up",
        shortcode: "point_up",
        category: Category::Gestures,
        tags: &["listen", "important", "one", "first"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👍",
        name: "thumbs up",
        shortcode: "thumbsup",
        category: Category::Gestures,
        tags: &["+1", "yes", "approve", "like", "good", "nice"],
        emoticons: &["(y)"],
    },
    EmojiEntry {
        glyph: "👎",
        name: "thumbs down",
        shortcode: "thumbsdown",
        category: Category::Gestures,
        tags: &["-1", "no", "disapprove", "dislike", "bad"],
        emoticons: &["(n)"],
    },
    EmojiEntry {
        glyph: "✊",
        name: "raised fist",
        shortcode: "fist_raised",
        category: Category::Gestures,
        tags: &["power", "solidarity", "strength", "resistance"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👊",
        name: "oncoming fist",
        shortcode: "punch",
        category: Category::Gestures,
        tags: &["fistbump", "brofist", "pound", "hit"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤛",
        name: "left-facing fist",
        shortcode: "fist_left",
        category: Category::Gestures,
        tags: &["fistbump", "left"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤜",
        name: "right-facing fist",
        shortcode: "fist_right",
        category: Category::Gestures,
        tags: &["fistbump", "right"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👏",
        name: "clapping hands",
        shortcode: "clap",
        category: Category::Gestures,
        tags: &["applause", "bravo", "praise", "great"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🙌",
        name: "raising hands",
        shortcode: "raised_hands",
        category: Category::Gestures,
        tags: &["celebrate", "praise", "hallelujah", "cheers"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👐",
        name: "open hands",
        shortcode: "open_hands",
        category: Category::Gestures,
        tags: &["hug", "open", "presenting"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤲",
        name: "palms up together",
        shortcode: "palms_up_together",
        category: Category::Gestures,
        tags: &["prayer", "request", "hope"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤝",
        name: "handshake",
        shortcode: "handshake",
        category: Category::Gestures,
        tags: &["deal", "partner", "agreement", "truce"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🙏",
        name: "folded hands",
        shortcode: "pray",
        category: Category::Gestures,
        tags: &["please", "thank you", "thanks", "gratitude", "namaste", "bless"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "✍️",
        name: "writing hand",
        shortcode: "writing_hand",
        category: Category::Gestures,
        tags: &["write", "note", "author", "compose"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💪",
        name: "flexed biceps",
        shortcode: "muscle",
        category: Category::Gestures,
        tags: &["strong", "power", "flex", "workout", "fitness", "tough"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // People & Characters
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🤷",
        name: "person shrugging",
        shortcode: "shrug",
        category: Category::People,
        tags: &["idk", "doubt", "clueless", "whatever", "who knows"],
        emoticons: &["¯\\_(ツ)_/¯"],
    },
    EmojiEntry {
        glyph: "🤦",
        name: "person facepalming",
        shortcode: "facepalm",
        category: Category::People,
        tags: &["smh", "disbelief", "facepalm", "duh"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👀",
        name: "eyes",
        shortcode: "eyes",
        category: Category::People,
        tags: &["look", "see", "watch", "peep", "inspect"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🧠",
        name: "brain",
        shortcode: "brain",
        category: Category::People,
        tags: &["mind", "intellect", "smart", "think", "iq"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🫀",
        name: "anatomical heart",
        shortcode: "anatomical_heart",
        category: Category::People,
        tags: &["heart", "cardio", "pulse"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🫁",
        name: "lungs",
        shortcode: "lungs",
        category: Category::People,
        tags: &["breath", "air", "respiration"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Animals & Nature
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🐱",
        name: "cat face",
        shortcode: "cat",
        category: Category::Animals,
        tags: &["kitten", "meow", "feline", "pet"],
        emoticons: &["=^.^="],
    },
    EmojiEntry {
        glyph: "😸",
        name: "grinning cat with smiling eyes",
        shortcode: "smile_cat",
        category: Category::Animals,
        tags: &["cat", "smile", "happy"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐶",
        name: "dog face",
        shortcode: "dog",
        category: Category::Animals,
        tags: &["puppy", "bark", "canine", "pet"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦊",
        name: "fox",
        shortcode: "fox",
        category: Category::Animals,
        tags: &["clever", "wild", "orange"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐻",
        name: "bear",
        shortcode: "bear",
        category: Category::Animals,
        tags: &["grizzly", "wild", "forest"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐼",
        name: "panda",
        shortcode: "panda",
        category: Category::Animals,
        tags: &["bamboo", "bear", "china"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐯",
        name: "tiger face",
        shortcode: "tiger",
        category: Category::Animals,
        tags: &["stripes", "wild", "cat", "feline"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐧",
        name: "penguin",
        shortcode: "penguin",
        category: Category::Animals,
        tags: &["linux", "tux", "ice", "bird"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦀",
        name: "crab",
        shortcode: "crab",
        category: Category::Animals,
        tags: &["rust", "rustacean", "ferris", "crustacean", "sea"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐛",
        name: "bug",
        shortcode: "bug",
        category: Category::Animals,
        tags: &["caterpillar", "defect", "glitch", "error", "insect"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦁",
        name: "lion",
        shortcode: "lion",
        category: Category::Animals,
        tags: &["king", "brave", "pride", "feline"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦅",
        name: "eagle",
        shortcode: "eagle",
        category: Category::Animals,
        tags: &["bird", "freedom", "predator", "fly"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐺",
        name: "wolf",
        shortcode: "wolf",
        category: Category::Animals,
        tags: &["canine", "howl", "pack", "lone wolf"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦉",
        name: "owl",
        shortcode: "owl",
        category: Category::Animals,
        tags: &["wise", "night", "wisdom", "nocturnal"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦇",
        name: "bat",
        shortcode: "bat",
        category: Category::Animals,
        tags: &["night", "cave", "batman", "spooky"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐍",
        name: "snake",
        shortcode: "snake",
        category: Category::Animals,
        tags: &["python", "serpent", "reptile", "danger"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🦈",
        name: "shark",
        shortcode: "shark",
        category: Category::Animals,
        tags: &["ocean", "predator", "jaws", "fish"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐙",
        name: "octopus",
        shortcode: "octopus",
        category: Category::Animals,
        tags: &["tentacles", "sea", "cephalopod", "kraken"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🐢",
        name: "turtle",
        shortcode: "turtle",
        category: Category::Animals,
        tags: &["slow", "shell", "tortoise", "steady"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔥",
        name: "fire",
        shortcode: "fire",
        category: Category::Nature,
        tags: &["flame", "hot", "lit", "burn", "blaze"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚡",
        name: "high voltage",
        shortcode: "zap",
        category: Category::Nature,
        tags: &["lightning", "bolt", "electric", "power", "energy", "fast"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "☀️",
        name: "sun",
        shortcode: "sun",
        category: Category::Nature,
        tags: &["day", "bright", "sunny", "warm", "morning"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🌙",
        name: "crescent moon",
        shortcode: "moon",
        category: Category::Nature,
        tags: &["night", "dark", "sleep", "lunar"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⭐",
        name: "star",
        shortcode: "star",
        category: Category::Nature,
        tags: &["favorite", "astronomy", "shine"],
        emoticons: &["*"],
    },
    EmojiEntry {
        glyph: "🌟",
        name: "glowing star",
        shortcode: "glowing_star",
        category: Category::Nature,
        tags: &["glimmer", "shine", "sparkle"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🌊",
        name: "water wave",
        shortcode: "wave_water",
        category: Category::Nature,
        tags: &["ocean", "sea", "tsunami", "water", "surf"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🌲",
        name: "evergreen tree",
        shortcode: "evergreen_tree",
        category: Category::Nature,
        tags: &["pine", "forest", "nature", "wood"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Food & Drink
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "☕",
        name: "hot beverage",
        shortcode: "coffee",
        category: Category::Food,
        tags: &["tea", "cafe", "espresso", "morning", "drink", "brew"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍵",
        name: "teacup without handle",
        shortcode: "tea",
        category: Category::Food,
        tags: &["green tea", "matcha", "drink"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍺",
        name: "beer mug",
        shortcode: "beer",
        category: Category::Food,
        tags: &["drink", "alcohol", "pub", "cheers"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍻",
        name: "clinking beer mugs",
        shortcode: "beers",
        category: Category::Food,
        tags: &["toast", "celebrate", "party"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍕",
        name: "pizza",
        shortcode: "pizza",
        category: Category::Food,
        tags: &["cheese", "slice", "fast food"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍔",
        name: "hamburger",
        shortcode: "burger",
        category: Category::Food,
        tags: &["burger", "beef", "cheeseburger"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🌮",
        name: "taco",
        shortcode: "taco",
        category: Category::Food,
        tags: &["mexican", "food", "tuesday"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🍿",
        name: "popcorn",
        shortcode: "popcorn",
        category: Category::Food,
        tags: &["movie", "snack", "drama", "watching"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Travel & Places
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🚀",
        name: "rocket",
        shortcode: "rocket",
        category: Category::Travel,
        tags: &["launch", "blastoff", "ship", "fast", "space", "deploy"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🛸",
        name: "flying saucer",
        shortcode: "flying_saucer",
        category: Category::Travel,
        tags: &["ufo", "alien", "space"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🛰️",
        name: "satellite",
        shortcode: "satellite_orbit",
        category: Category::Travel,
        tags: &["space", "orbit", "gps", "comms"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🌐",
        name: "globe with meridians",
        shortcode: "globe",
        category: Category::Travel,
        tags: &["world", "internet", "web", "network", "mesh", "earth"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🗺️",
        name: "world map",
        shortcode: "map",
        category: Category::Travel,
        tags: &["location", "travel", "geography", "plan"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🚗",
        name: "automobile",
        shortcode: "car",
        category: Category::Travel,
        tags: &["vehicle", "drive", "road"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "✈️",
        name: "airplane",
        shortcode: "airplane",
        category: Category::Travel,
        tags: &["flight", "fly", "plane", "travel"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Activities & Sports
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🎉",
        name: "party popper",
        shortcode: "party",
        category: Category::Activities,
        tags: &["tada", "celebrate", "congrats", "cheers", "woo", "win"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎊",
        name: "confetti ball",
        shortcode: "confetti_ball",
        category: Category::Activities,
        tags: &["celebration", "festive"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎯",
        name: "bullseye",
        shortcode: "target",
        category: Category::Activities,
        tags: &["goal", "aim", "direct", "accuracy", "hit", "focus"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🏆",
        name: "trophy",
        shortcode: "trophy",
        category: Category::Activities,
        tags: &["winner", "first", "champion", "award", "prize"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🥇",
        name: "1st place medal",
        shortcode: "medal_first",
        category: Category::Activities,
        tags: &["gold", "first", "champion"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎮",
        name: "video game",
        shortcode: "game",
        category: Category::Activities,
        tags: &["controller", "play", "gaming", "arcade"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎲",
        name: "game die",
        shortcode: "dice",
        category: Category::Activities,
        tags: &["random", "luck", "chance", "roll"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Objects, Tools & Tech
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🛡️",
        name: "shield",
        shortcode: "shield",
        category: Category::Objects,
        tags: &["defense", "protect", "sovereign", "security", "guard", "armor", "firewall"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💡",
        name: "light bulb",
        shortcode: "idea",
        category: Category::Objects,
        tags: &["bulb", "light", "thought", "inspiration", "brainstorm", "eureka"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💻",
        name: "laptop",
        shortcode: "laptop",
        category: Category::Objects,
        tags: &["computer", "pc", "workstation", "dev", "tech", "coding"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🖥️",
        name: "desktop computer",
        shortcode: "desktop",
        category: Category::Objects,
        tags: &["pc", "monitor", "screen", "workstation"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📱",
        name: "mobile phone",
        shortcode: "phone",
        category: Category::Objects,
        tags: &["cell", "smartphone", "android", "iphone", "mobile"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⌨️",
        name: "keyboard",
        shortcode: "keyboard",
        category: Category::Objects,
        tags: &["type", "keys", "input", "dev"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💾",
        name: "floppy disk",
        shortcode: "disk",
        category: Category::Objects,
        tags: &["save", "storage", "floppy", "drive"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📦",
        name: "package",
        shortcode: "package",
        category: Category::Objects,
        tags: &["box", "crate", "parcel", "cargo", "delivery", "shipping", "binary"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔨",
        name: "hammer",
        shortcode: "hammer",
        category: Category::Objects,
        tags: &["tool", "build", "forge", "fix"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔧",
        name: "wrench",
        shortcode: "wrench",
        category: Category::Objects,
        tags: &["tool", "spanner", "fix", "repair", "config", "settings"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚙️",
        name: "gear",
        shortcode: "gear",
        category: Category::Objects,
        tags: &["cog", "settings", "options", "machine", "system"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📡",
        name: "satellite antenna",
        shortcode: "satellite",
        category: Category::Objects,
        tags: &["dish", "signal", "radio", "radar", "comm", "network"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔒",
        name: "locked",
        shortcode: "lock",
        category: Category::Objects,
        tags: &["secure", "closed", "private", "custody", "safe"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔓",
        name: "unlocked",
        shortcode: "unlock",
        category: Category::Objects,
        tags: &["open", "free", "access"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔑",
        name: "key",
        shortcode: "key",
        category: Category::Objects,
        tags: &["password", "secret", "unlock", "crypto", "auth"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🗝️",
        name: "old key",
        shortcode: "old_key",
        category: Category::Objects,
        tags: &["vintage", "antique", "secret"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔋",
        name: "battery",
        shortcode: "battery",
        category: Category::Objects,
        tags: &["power", "energy", "charge"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🪫",
        name: "low battery",
        shortcode: "low_battery",
        category: Category::Objects,
        tags: &["depleted", "recharge", "exhausted"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⏱️",
        name: "stopwatch",
        shortcode: "stopwatch",
        category: Category::Objects,
        tags: &["timer", "time", "speed", "clock", "bench"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⏳",
        name: "hourglass not done",
        shortcode: "hourglass",
        category: Category::Objects,
        tags: &["wait", "loading", "time", "pending"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💎",
        name: "gem stone",
        shortcode: "gem",
        category: Category::Objects,
        tags: &["diamond", "crystal", "precious", "jewel"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🪙",
        name: "coin",
        shortcode: "coin",
        category: Category::Objects,
        tags: &["money", "gold", "token", "currency"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💰",
        name: "money bag",
        shortcode: "money",
        category: Category::Objects,
        tags: &["cash", "dollar", "wealth", "payment", "revenue"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💳",
        name: "credit card",
        shortcode: "card",
        category: Category::Objects,
        tags: &["payment", "bank", "stripe", "charge", "debit"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📊",
        name: "bar chart",
        shortcode: "chart",
        category: Category::Objects,
        tags: &["analytics", "graph", "stats", "metrics"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📈",
        name: "chart increasing",
        shortcode: "stonks",
        category: Category::Objects,
        tags: &["growth", "up", "bull", "trend", "rise", "increase"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📉",
        name: "chart decreasing",
        shortcode: "notstonks",
        category: Category::Objects,
        tags: &["down", "bear", "decline", "fall", "loss"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔍",
        name: "magnifying glass left",
        shortcode: "search",
        category: Category::Objects,
        tags: &["find", "query", "seek", "inspect", "zoom"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔎",
        name: "magnifying glass right",
        shortcode: "recon",
        category: Category::Objects,
        tags: &["find", "investigate", "audit", "recon", "census"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📜",
        name: "scroll",
        shortcode: "scroll",
        category: Category::Objects,
        tags: &["doc", "document", "contract", "paper", "manifesto"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📄",
        name: "page facing up",
        shortcode: "doc",
        category: Category::Objects,
        tags: &["file", "document", "sheet", "page"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "📁",
        name: "file folder",
        shortcode: "folder",
        category: Category::Objects,
        tags: &["dir", "directory", "files"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🏷️",
        name: "label",
        shortcode: "tag",
        category: Category::Objects,
        tags: &["badge", "label", "ticket"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔗",
        name: "link",
        shortcode: "link",
        category: Category::Objects,
        tags: &["url", "chain", "connect", "hyperlink"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🧰",
        name: "toolbox",
        shortcode: "toolbox",
        category: Category::Objects,
        tags: &["tools", "kit", "equipment"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🪓",
        name: "axe",
        shortcode: "axe",
        category: Category::Objects,
        tags: &["chop", "wood", "weapon", "cut"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🗡️",
        name: "dagger",
        shortcode: "dagger",
        category: Category::Objects,
        tags: &["blade", "sword", "knife", "sharp"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚔️",
        name: "crossed swords",
        shortcode: "swords",
        category: Category::Objects,
        tags: &["battle", "fight", "combat", "war"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🏹",
        name: "bow and arrow",
        shortcode: "bow_and_arrow",
        category: Category::Objects,
        tags: &["archery", "target", "weapon"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Symbols & Indicators
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "✅",
        name: "check mark button",
        shortcode: "check",
        category: Category::Symbols,
        tags: &["done", "pass", "ok", "success", "yes", "correct", "verified"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "❌",
        name: "cross mark",
        shortcode: "cross",
        category: Category::Symbols,
        tags: &["no", "fail", "wrong", "cancel", "x", "delete", "bad"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚠️",
        name: "warning",
        shortcode: "warning",
        category: Category::Symbols,
        tags: &["alert", "caution", "danger", "hazard"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🚨",
        name: "police car light",
        shortcode: "siren",
        category: Category::Symbols,
        tags: &["alarm", "emergency", "alert", "police", "warning"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🟢",
        name: "green circle",
        shortcode: "green_circle",
        category: Category::Symbols,
        tags: &["online", "live", "ok", "healthy", "up", "green"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🟡",
        name: "yellow circle",
        shortcode: "yellow_circle",
        category: Category::Symbols,
        tags: &["warning", "degraded", "idle", "caution", "yellow"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔴",
        name: "red circle",
        shortcode: "red_circle",
        category: Category::Symbols,
        tags: &["offline", "error", "down", "critical", "stop", "red"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔵",
        name: "blue circle",
        shortcode: "blue_circle",
        category: Category::Symbols,
        tags: &["info", "blue", "primary"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🟣",
        name: "purple circle",
        shortcode: "purple_circle",
        category: Category::Symbols,
        tags: &["purple", "violet"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚫",
        name: "black circle",
        shortcode: "black_circle",
        category: Category::Symbols,
        tags: &["dark", "black"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "⚪",
        name: "white circle",
        shortcode: "white_circle",
        category: Category::Symbols,
        tags: &["light", "white"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💯",
        name: "hundred points",
        shortcode: "100",
        category: Category::Symbols,
        tags: &["hundred", "score", "perfect", "keepit100"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "✨",
        name: "sparkles",
        shortcode: "sparkles",
        category: Category::Symbols,
        tags: &["magic", "shine", "stars", "new", "clean", "sparkle"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "❤️",
        name: "red heart",
        shortcode: "heart",
        category: Category::Symbols,
        tags: &["love", "like", "affection", "passion"],
        emoticons: &["<3"],
    },
    EmojiEntry {
        glyph: "💔",
        name: "broken heart",
        shortcode: "broken_heart",
        category: Category::Symbols,
        tags: &["heartbreak", "sad", "breakup"],
        emoticons: &["</3"],
    },
    EmojiEntry {
        glyph: "💙",
        name: "blue heart",
        shortcode: "blue_heart",
        category: Category::Symbols,
        tags: &["loyalty", "trust", "blue"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💚",
        name: "green heart",
        shortcode: "green_heart",
        category: Category::Symbols,
        tags: &["nature", "healthy", "green"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💛",
        name: "yellow heart",
        shortcode: "yellow_heart",
        category: Category::Symbols,
        tags: &["friendship", "warmth", "yellow"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🖤",
        name: "black heart",
        shortcode: "black_heart",
        category: Category::Symbols,
        tags: &["dark", "goth", "sorrow"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🤍",
        name: "white heart",
        shortcode: "white_heart",
        category: Category::Symbols,
        tags: &["peace", "pure", "white"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💤",
        name: "zzz",
        shortcode: "zzz",
        category: Category::Symbols,
        tags: &["sleep", "tired", "rest", "night"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💥",
        name: "collision",
        shortcode: "boom",
        category: Category::Symbols,
        tags: &["blast", "explode", "bang", "pow"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💢",
        name: "anger symbol",
        shortcode: "anger_symbol",
        category: Category::Symbols,
        tags: &["vein", "angry", "furious"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "💬",
        name: "speech balloon",
        shortcode: "speech_balloon",
        category: Category::Symbols,
        tags: &["chat", "message", "talk", "dialog"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "👁️‍🗨️",
        name: "eye in speech bubble",
        shortcode: "witness",
        category: Category::Symbols,
        tags: &["anti-bullying", "witness", "observation"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔔",
        name: "bell",
        shortcode: "bell",
        category: Category::Symbols,
        tags: &["notification", "alert", "chime", "sound"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🔕",
        name: "bell with slash",
        shortcode: "no_bell",
        category: Category::Symbols,
        tags: &["mute", "silent", "quiet", "dnd"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎵",
        name: "musical note",
        shortcode: "musical_note",
        category: Category::Symbols,
        tags: &["music", "song", "tune", "sound"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🎶",
        name: "musical notes",
        shortcode: "notes",
        category: Category::Symbols,
        tags: &["music", "melody", "audio"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "➕",
        name: "plus",
        shortcode: "plus",
        category: Category::Symbols,
        tags: &["add", "more", "positive"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "➖",
        name: "minus",
        shortcode: "minus",
        category: Category::Symbols,
        tags: &["subtract", "less", "negative"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "♾️",
        name: "infinity",
        shortcode: "infinity",
        category: Category::Symbols,
        tags: &["forever", "endless", "limitless"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "❓",
        name: "red question mark",
        shortcode: "question",
        category: Category::Symbols,
        tags: &["help", "confused", "what", "query"],
        emoticons: &["?"],
    },
    EmojiEntry {
        glyph: "❗",
        name: "red exclamation mark",
        shortcode: "exclamation",
        category: Category::Symbols,
        tags: &["important", "attention", "urgent", "notice"],
        emoticons: &["!"],
    },
    EmojiEntry {
        glyph: "ℹ️",
        name: "information",
        shortcode: "info",
        category: Category::Symbols,
        tags: &["details", "help", "notice", "about"],
        emoticons: &[],
    },

    // -------------------------------------------------------------------------
    // Flags
    // -------------------------------------------------------------------------
    EmojiEntry {
        glyph: "🏁",
        name: "chequered flag",
        shortcode: "checkered_flag",
        category: Category::Flags,
        tags: &["finish", "race", "done", "winner"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🚩",
        name: "triangular flag",
        shortcode: "red_flag",
        category: Category::Flags,
        tags: &["warning", "flag", "marker", "bad"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🏴",
        name: "black flag",
        shortcode: "black_flag",
        category: Category::Flags,
        tags: &["pirate", "rebel", "anarchy"],
        emoticons: &[],
    },
    EmojiEntry {
        glyph: "🏳️",
        name: "white flag",
        shortcode: "white_flag",
        category: Category::Flags,
        tags: &["surrender", "peace"],
        emoticons: &[],
    },
];
